default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
        - id: clang-format
          args: ['--style=file']
          types_or: []
          types: [text]
          files: \.(cpp|cxx|c|h|hpp|hxx|txx)$
