[project]
name = "obelisk-debug"
authors = [
    "Albert Li <alberthli@caltech.edu>",
    "Zach Olkin <zolkin@caltech.edu>",
]
channels = ["conda-forge"]
platforms = ["linux-64"]

[feature.empty]

[environments]
empty = ["empty"]