# ########### #
# BOILERPLATE #
# ########### #

[project]
name = "obelisk"
authors = [
    "Albert Li <alberthli@caltech.edu>",
    "Zach Olkin <zolkin@caltech.edu>",
]
description = "The AMBER Lab's generic robot control interface."
channels = [
    "nvidia",
    "pytorch",
    "nvidia/label/cuda-12.1.0",
    "nvidia/label/cuda-11.8.0",
    "conda-forge",
    "robostack",
]
platforms = ["linux-64"]


# ############ #
# FEATURE SETS #
# ############ #

# minimal
[dependencies]
python = ">=3.10"
pip = ">=24.0"

[pypi-dependencies]
matplotlib=">=3.9.0"
numpy=">=2.0.0"
obelisk_py = { path = "./obelisk/python", editable = true }


# cuda
[feature.cuda118]
system-requirements = {cuda = "11.8.0"}

[feature.cuda118.dependencies]
cuda = { version = "*", channel="nvidia/label/cuda-11.8.0" }

[feature.cuda121]
system-requirements = {cuda = "12.1.0"}

[feature.cuda121.dependencies]
cuda = { version = "*", channel="nvidia/label/cuda-12.1.0" }


# torch
[feature.torch118]
dependencies = {pytorch-cuda="11.8.0"}
pypi-dependencies = { torchvision=">=0.18.1", tqdm=">=4.66.4" }

[feature.torch121]
dependencies = {pytorch-cuda="12.1.0"}
pypi-dependencies = { torchvision=">=0.18.1", tqdm=">=4.66.4" }


# docs
[feature.docs.pypi-dependencies]
myst-parser=">=3.0.1"
sphinx=">=7.3.7"
sphinx-rtd-theme=">=2.0.0"


# test
[feature.test.pypi-dependencies]
pytest=">=7.1.2"


# dev
[feature.dev.pypi-dependencies]
pre-commit=">=3.7.1"
pytest-xdist=">=3.6.1"
typeguard=">=4.3.0"
ruff=">=0.4.9"
pyright=">=1.1.367"


# ################ #
# ENVIRONMENT SETS #
# ################ #

[environments]
default = { solve-group = "default" }

# torch
torch118 = { features=["cuda118", "torch118"], solve-group="cuda118" }
torch121 = { features=["cuda121", "torch121"], solve-group="cuda121" }

# test
test-workflow = { features=["test", "dev"], solve-group="default" }
test = { features=["cuda121", "torch121", "test"], solve-group="cuda121" }

# dev
dev = { features=["cuda121", "torch121", "docs", "test", "dev"], solve-group="cuda121" }

# ##### #
# TASKS #
# ##### #
