config: dummy
onboard:
  control:
    - pkg: obelisk_control_cpp
      executable: example_position_setpoint_controller
      params_path: /obelisk_ws/src/obelisk_ros/config/dummy_params.txt
      callback_groups:
        test_cbg: MutuallyExclusiveCallbackGroup
      params:
        test_param: value_configured_in_yaml
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/dummy/ctrl
          history_depth: 10
          callback_group: None
      # ----- Joystick publisher ----- #
        - ros_parameter: joystick_feedback_setting
          topic: /obelisk/dummy/joy_feedback
      subscribers:
        - ros_parameter: sub_est_setting
          topic: /obelisk/dummy/est
          history_depth: 10
          callback_group: None
      # ----- Joystick subscriber ----- #
        - ros_parameter: joystick_sub_setting
          topic: /obelisk/dummy/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.001
          callback_group: test_cbg
  estimation:
    - pkg: obelisk_estimation_cpp
      executable: jointencoders_passthrough_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/dummy/est
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_sensor_setting
          topic: /obelisk/dummy/joint_encoders
          msg_type: JointEncoders
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None
  # sensing:
  robot:
    - is_simulated: True
      pkg: obelisk_sim_cpp
      executable: obelisk_mujoco_robot
      params:
        ic_keyframe: ic
        height_map_grid_size: [1., 1.]
        height_map_grid_spacing: 0.1
        height_map_geom_group: [0]
        # camera_name: "fixed_cam"  # You can select a camera to use here
      publishers:
        - ros_parameter: pub_true_sim_state_setting
          topic: /obelisk/dummy/true_sim_state
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_true_sim_state_setting
          history_depth: 10
          timer_period_sec: 0.01
          callback_group: None
      subscribers:
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/dummy/ctrl
          msg_type: PositionSetpoint
          history_depth: 10
          callback_group: None
      sim:
        - ros_parameter: mujoco_setting
          num_steps_per_viz: 5
          robot_pkg: dummy_bot
          model_xml_path: dummy.xml
          sensor_settings:
          - topic: /obelisk/dummy/joint_encoders
            dt: 0.001
            msg_type: ObkJointEncoders
            sensor_names:
              joint_pos: jointpos
              joint_vel: jointvel
          - topic: /obelisk/dummy/imu
            dt: 0.002
            msg_type: ObkImu
            sensor_names:
              tip_acc_sensor: accelerometer
              tip_gyro_sensor: gyro
              tip_frame_sensor: framequat
          - topic: /obelisk/dummy/framepose
            dt: 0.002
            msg_type: PoseStamped
            sensor_names:
              tip_pos_sensor: framepos
              tip_orientation_sensor: framequat
          - topic: /obelisk/dummy/odom
            dt: 0.005
            msg_type: Odometry
            sensor_names:
              tip_pos_sensor: framepos
              tip_orientation_sensor: framequat
              tip_velocimeter: velocimeter
              tip_gyro_sensor: gyro
          - topic: /obelisk/dummy/scan_dots
            dt: 0.1
            msg_type: GridCells
            sensor_names:
              tip_pos_sensor: framepos
  joystick:
    on: True
    pub_topic: /obelisk/dummy/joy
    sub_topic: /obelisk/dummy/joy_feedback
