config: dummy
onboard:
  control:
    - pkg: obelisk_control_cpp
      executable: example_position_setpoint_controller
      params_path: /obelisk_ws/src/obelisk_ros/config/dummy_params.txt
      # callback_groups:
      params:
        test_param: value_configured_in_yaml
      publishers:
        - ros_parameter: pub_ctrl_setting
          # key: pub1
          topic: /obelisk/dummy/ctrl
          msg_type: PositionSetpoint
          history_depth: 10
          callback_group: None
          non_obelisk: False
      subscribers:
        - ros_parameter: sub_est_setting
          # key: sub1
          topic: /obelisk/dummy/est
          msg_type: EstimatedState
          history_depth: 10
          # callback_key: sub_callback1
          callback_group: None
          non_obelisk: False
      timers:
        - ros_parameter: timer_ctrl_setting
          # key: timer1
          timer_period_sec: 0.001
          callback_group: None
          # callback_key: timer_callback1
  estimation:
    - pkg: obelisk_estimation_cpp
      executable: jointencoders_passthrough_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          # key: pub1
          topic: /obelisk/dummy/est
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
          non_obelisk: False
      subscribers:
        - ros_parameter: sub_sensor_setting
          # key: sub1
          topic: /obelisk/dummy/joint_encoders
          msg_type: JointEncoders
          history_depth: 10
          # callback_key: sub_callback1
          callback_group: None
          non_obelisk: False
      timers:
        - ros_parameter: timer_est_setting
          # key: timer1
          timer_period_sec: 0.001
          callback_group: None
          # callback_key: timer_callback1
  # sensing:
  robot:
    - is_simulated: True
      pkg: obelisk_sim_cpp
      executable: obelisk_mujoco_robot
      params:
        ic_keyframe: ic
      # callback_groups:
      # publishers:
      subscribers:
        - ros_parameter: sub_ctrl_setting
          # key: sub1
          topic: /obelisk/dummy/ctrl
          msg_type: PositionSetpoint
          history_depth: 10
          # callback_key: sub_callback1
          callback_group: None
          non_obelisk: False
      sim:
        - ros_parameter: mujoco_setting
          n_u: 1
          time_step: 0.002
          num_steps_per_viz: 5
          robot_pkg: dummy_bot
          model_xml_path: dummy.xml
          sensor_settings:
          - topic: /obelisk/dummy/joint_encoders
            dt: 0.001
            msg_type: ObkJointEncoders
            sensor_names:
              joint_pos: jointpos
              joint_vel: jointvel
          - topic: /obelisk/dummy/imu
            dt: 0.002
            msg_type: ObkImu
            sensor_names:
              tip_acc_sensor: accelerometer
              tip_gyro_sensor: gyro
              tip_frame_sensor: framequat
          - topic: /obelisk/dummy/framepose
            dt: 0.002
            msg_type: ObkFramePose
            sensor_names:
              tip_pos_sensor: framepos
              tip_orientation_sensor: framequat
