- serial_number: 12746523
  resolution: "VGA"
  fps: 100
  depth: True
  type: "zedmini"
  side: "left"
- serial_number: 14390641
  resolution: "VGA"
  fps: 100
  depth: True
  type: "zedmini"
  side: "left"
- serial_number: 19798856
  resolution: "VGA"
  fps: 100
  depth: True
  type: "zedmini"
  side: "left"
