config: dummy
onboard:
  control:
    pkg: obelisk_control_cpp
    executable: example_position_setpoint_controller
    # callback_groups:
    publishers:
      - ros_parameter: pub_ctrl_setting
        # key: pub1
        topic: /obelisk/dummy/ctrl
        msg_type: PositionSetpoint
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_est_setting
        # key: sub1
        topic: /obelisk/dummy/est
        msg_type: EstimatedState
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_ctrl_setting
        # key: timer1
        timer_period_sec: 0.001
        callback_group: None
        # callback_key: timer_callback1
  estimation:
    pkg: obelisk_estimation_cpp
    executable: jointencoders_passthrough_estimator
    # callback_groups:
    publishers:
      - ros_parameter: pub_est_setting
        # key: pub1
        topic: /obelisk/dummy/est
        msg_type: EstimatedState
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_sensor_setting
        # key: sub1
        topic: /obelisk/dummy/sensor
        msg_type: JointEncoders
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_est_setting
        # key: timer1
        timer_period_sec: 0.001
        callback_group: None
        # callback_key: timer_callback1
  # sensing:
  robot:
    is_simulated: True
    pkg: obelisk_sim_cpp
    executable: obelisk_mujoco_robot
    # callback_groups:
    # publishers:
    subscribers:
      - ros_parameter: sub_ctrl_setting
        # key: sub1
        topic: /obelisk/dummy/ctrl
        msg_type: PositionSetpoint
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    sim:
      - ros_parameter: mujoco_setting
        model_xml_path: dummy/dummy.xml
        n_u: 1
        time_step: 0.002
        num_steps_per_viz: 5
        sensor_settings:
        - topic: /obelisk/dummy/sensor
          dt: 0.001
          sensor_type: jointpos
          sensor_names:
          - sensor_joint1
  viz:
    on: True
    viz_tool: rviz
    rviz_pkg: obelisk_ros
    rviz_config: basic_obk_config.rviz
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: g1_description
        urdf: g1.urdf
        robot_topic: g1_description
        tf_prefix: g1
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: estimated_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states_g1
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.05
            callback_group: None
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: go2_description
        urdf: go2_description.urdf
        robot_topic: go2_description
        tf_prefix: go2
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: estimated_state2
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states_go2
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.05
            callback_group: None
