onboard:
  control:
    impl: python
    executable: example_position_setpoint_controller
    # callback_groups:
    publishers:
      - ros_parameter: pub_ctrl_setting
        # key: pub1
        topic: /obelisk/dummy/ctrl
        msg_type: PositionSetpoint
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_est_setting
        # key: sub1
        topic: /obelisk/dummy/est
        msg_type: EstimatedState
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_ctrl_setting
        # key: timer1
        timer_period_sec: 0.001
        callback_group: None
        # callback_key: timer_callback1
  estimation:
    impl: python
    executable: jointencoders_passthrough_estimator
    # callback_groups:
    publishers:
      - ros_parameter: pub_est_setting
        # key: pub1
        topic: /obelisk/dummy/est
        msg_type: EstimatedState
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_sensor_setting
        # key: sub1
        topic: /obelisk/dummy/sensor
        msg_type: JointEncoders
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_est_setting
        # key: timer1
        timer_period_sec: 0.01
        callback_group: None
        # callback_key: timer_callback1
  # sensing:
  robot:
    is_simulated: True
    impl: python
    executable: obelisk_mujoco_robot
    # callback_groups:
    # publishers:
    subscribers:
      - ros_parameter: sub_ctrl_setting
        # key: sub1
        topic: /obelisk/dummy/ctrl
        msg_type: PositionSetpoint
        history_depth: 10
        # callback_key: sub_callback1
        callback_group: None
        non_obelisk: False
    # timers:
    sim:
      - ros_parameter: mujoco_setting
        model_xml_path: dummy/dummy.xml
        n_u: 1
        time_step: 0.002
        num_steps_per_viz: 10
        sensor_settings:
        - topic: /obelisk/dummy/sensor
          dt: 0.01
          sensor_type: jointpos
          sensor_names:
          - sensor_joint1
