config: go2_example
onboard:
  control:
  # ----- Low Level Controller ----- #
    - pkg: obelisk_unitree_cpp
      params:
        robot_str: Go2
      executable: unitree_example_controller
      # callback_groups:
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/ctrl
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/est_state
          history_depth: 10
          callback_group: None
        # ----- Joystick subscriber ----- #
        - ros_parameter: joystick_sub_setting
          topic: /obelisk/go2/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.001
          callback_group: None
  # ----- High Level/Execution FSM Controller ----- #
    - pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_joystick
      # callback_groups:
      publishers:
      # ----- Execution FSM ----- #
        - ros_parameter: pub_exec_fsm_setting
          topic: /obelisk/go2/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/go2/high_level_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
      # ----- Joystick subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/go2/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.01
          callback_group: None
  estimation:
    - pkg: obelisk_unitree_cpp
      executable: unitree_example_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/go2/est_state
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_sensor_setting
          topic: /obelisk/go2/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None
  # sensing:
  robot:
    # === simulation ===
    # - is_simulated: True
    #   pkg: obelisk_unitree_cpp
    #   executable: obelisk_unitree_sim
    #   params:
    #     ic_keyframe: standing
    # === hardware ===
    - is_simulated: False
      pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_go2_hardware
      params:
        network_interface_name: enx001cc24ce09a
        default_kp: [
                    25., 25., 25.,    # FR
                    25., 25., 25.,    # FL
                    25., 25., 25.,    # RR
                    25., 25., 25.,    # RL
                    ]
        default_kd: [
                    1., 1., 1.,       # FR
                    1., 1., 1.,       # FL
                    1., 1., 1.,       # RR
                    1., 1., 1.,       # RL
        ]
    # ==================
      # callback_groups:
      publishers:
      # ----- Joints ----- #
        - ros_parameter: pub_sensor_setting
          topic: /obelisk/go2/joint_encoders
          history_depth: 10
      # ----- IMU ----- #
        - ros_parameter: pub_imu_setting
          topic: /obelisk/go2/torso_imu
          history_depth: 10
      # ----- Odom ----- #
        # - ros_parameter: pub_odom_setting
        #   topic: /obelisk/go2/odom
        #   history_depth: 10
      subscribers:
      # ----- Control ----- #
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/go2/ctrl
          history_depth: 10
          callback_group: None
      # ----- Execution FSM ----- #
        - ros_parameter: sub_fsm_setting
          topic: /obelisk/go2/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: sub_high_level_ctrl_setting
          topic: /obelisk/go2/high_level_ctrl
          history_depth: 10
          callback_group: None
      sim:
        - ros_parameter: mujoco_setting
          n_u: 16
          time_step: 0.002
          num_steps_per_viz: 5
          robot_pkg: go2_description
          model_xml_path: go2_fixed_base.xml
          sensor_settings:
          - topic: /obelisk/go2/joint_encoders
            dt: 0.002
            msg_type: ObkJointEncoders
            sensor_names:
            # ---------- Joint Positions ---------- #
              FR_hip_joint_pos_sensor: jointpos
              FR_thigh_joint_pos_sensor: jointpos
              FR_calf_joint_pos_sensor: jointpos

              FL_hip_joint_pos_sensor: jointpos
              FL_thigh_joint_pos_sensor: jointpos
              FL_calf_joint_pos_sensor: jointpos

              RR_hip_joint_pos_sensor: jointpos
              RR_thigh_joint_pos_sensor: jointpos
              RR_calf_joint_pos_sensor: jointpos

              RL_hip_joint_pos_sensor: jointpos
              RL_thigh_joint_pos_sensor: jointpos
              RL_calf_joint_pos_sensor: jointpos
            # ---------- Joint Velocities ---------- #
              FR_hip_joint_vel_sensor: jointvel
              FR_thigh_joint_vel_sensor: jointvel
              FR_calf_joint_vel_sensor: jointvel

              FL_hip_joint_vel_sensor: jointvel
              FL_thigh_joint_vel_sensor: jointvel
              FL_calf_joint_vel_sensor: jointvel

              RR_hip_joint_vel_sensor: jointvel
              RR_thigh_joint_vel_sensor: jointvel
              RR_calf_joint_vel_sensor: jointvel

              RL_hip_joint_vel_sensor: jointvel
              RL_thigh_joint_vel_sensor: jointvel
              RL_calf_joint_vel_sensor: jointvel
      timers:
        - ros_parameter: timer_sensor_setting
          timer_period_sec: 0.02
          callback_group: None
  viz:
    on: True
    viz_tool: foxglove
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: go2_description
        urdf: go2.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/go2/est_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.01
            callback_group: None
  joystick:
    on: True
    pub_topic: /obelisk/go2/joy
    sub_topic: /obelisk/go2/joy_feedback
