config: leap
onboard:
  control:
    - pkg: obelisk_leap_cpp
      executable: leap_example_controller
      # callback_groups:
      publishers:
        - ros_parameter: pub_ctrl_setting
          # key: pub1
          topic: /obelisk/leap/ctrl
          msg_type: PositionSetpoint
          history_depth: 10
          callback_group: None
          non_obelisk: False
      subscribers:
        - ros_parameter: sub_est_setting
          # key: sub1
          topic: /obelisk/leap/est
          msg_type: EstimatedState
          history_depth: 10
          # callback_key: sub_callback1
          callback_group: None
          non_obelisk: False
      timers:
        - ros_parameter: timer_ctrl_setting
          # key: timer1
          timer_period_sec: 0.001
          callback_group: None
          # callback_key: timer_callback1
  estimation:
    - pkg: obelisk_leap_cpp
      executable: leap_example_state_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          # key: pub1
          topic: /obelisk/leap/est
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
          non_obelisk: False
      subscribers:
        - ros_parameter: sub_sensor_setting
          # key: sub1
          topic: /obelisk/leap/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          # callback_key: sub_callback1
          callback_group: None
          non_obelisk: False
      timers:
        - ros_parameter: timer_est_setting
          # key: timer1
          timer_period_sec: 0.001
          callback_group: None
          # callback_key: timer_callback1
  # sensing:
  robot:
    # === simulation ===
    - is_simulated: True
      pkg: obelisk_sim_cpp
      executable: obelisk_mujoco_robot
    # === hardware ===
    # - is_simulated: False
    #   pkg: obelisk_leap_cpp
    #   executable: obelisk_leap_robot
    # ==================
      # callback_groups:
      params:
        KP: 150
        KI: 0
        KD: 50
      publishers:
        - ros_parameter: pub_sensor_setting
          topic: /obelisk/leap/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
          non_obelisk: False
      subscribers:
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/leap/ctrl
          msg_type: PositionSetpoint
          history_depth: 10
          callback_group: None
          non_obelisk: False
      sim:
        - ros_parameter: mujoco_setting
          n_u: 16
          time_step: 0.002
          num_steps_per_viz: 5
          robot_pkg: leap_rh
          model_xml_path: leap_rh_mounted.xml
          sensor_settings:
          - topic: /obelisk/leap/joint_encoders
            dt: 0.002
            msg_type: ObkJointEncoders
            sensor_names:
              if_mcp_sensor: jointpos
              if_rot_sensor: jointpos
              if_pip_sensor: jointpos
              if_dip_sensor: jointpos
              mf_mcp_sensor: jointpos
              mf_rot_sensor: jointpos
              mf_pip_sensor: jointpos
              mf_dip_sensor: jointpos
              rf_mcp_sensor: jointpos
              rf_rot_sensor: jointpos
              rf_pip_sensor: jointpos
              rf_dip_sensor: jointpos
              th_cmc_sensor: jointpos
              th_axl_sensor: jointpos
              th_mcp_sensor: jointpos
              th_ipl_sensor: jointpos
      timers:
        - ros_parameter: timer_sensor_setting
          timer_period_sec: 0.02
          callback_group: None

  viz:
    on: True
    viz_tool: foxglove
    rviz_pkg: obelisk_ros
    rviz_config: basic_obk_config.rviz
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        params:
          quat_order: wxyz
        robot_pkg: leap_rh
        urdf: leap_rh.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/leap/est
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: /obelisk/viz/joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.05
            callback_group: None
