config: leap
onboard:
  control:
    pkg: obelisk_control_py
    executable: leap_controller
    # callback_groups:
    publishers:
      - ros_parameter: pub_ctrl_setting
        topic: /obelisk/leap/ctrl
        msg_type: PositionSetpoint
        key: "asdf"
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_est_setting
        topic: /obelisk/leap/est
        msg_type: EstimatedState
        history_depth: 10
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_ctrl_setting
        timer_period_sec: 0.001
        callback_group: None
  estimation:
    pkg: obelisk_estimation_py
    executable: jointencoders_passthrough_estimator
    # callback_groups:
    publishers:
      - ros_parameter: pub_est_setting
        topic: /obelisk/leap/est
        msg_type: EstimatedState
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_sensor_setting
        # key: sub1
        topic: /obelisk/leap/sensor
        msg_type: JointEncoders
        history_depth: 10
        callback_group: None
        non_obelisk: False
    timers:
      - ros_parameter: timer_est_setting
        timer_period_sec: 0.001
        callback_group: None
  # sensing:
  robot:
    # `is_simulated` is critical for parsing correct package in the obelisk launch file

    # === simulation ===
    # is_simulated: False
    # pkg: obelisk_leap_py
    # executable: obelisk_leap_hand
    # === hardware ===
    is_simulated: True
    pkg: obelisk_sim_py
    executable: obelisk_mujoco_robot
    # ==================

    # callback_groups:
    publishers:
      - ros_parameter: pub_sensor_setting
        topic: /obelisk/leap/sensor
        msg_type: JointEncoders
        history_depth: 10
        callback_group: None
        non_obelisk: False
    subscribers:
      - ros_parameter: sub_ctrl_setting
        # key: sub1
        topic: /obelisk/leap/ctrl
        msg_type: PositionSetpoint
        history_depth: 10
        callback_group: None
        non_obelisk: False
    sim:
      - ros_parameter: mujoco_setting
        model_xml_path: leap/leap_hand.xml
        n_u: 16
        time_step: 0.002
        num_steps_per_viz: 5
        sensor_settings:
        - topic: /obelisk/leap/sensor
          dt: 0.001
          sensor_type: jointpos
          sensor_names:
          - trace1
    timers:
      - ros_parameter: timer_sensor_setting
        timer_period_sec: 0.02
        callback_group: None
