site_name: "pelvis_mocap_site"
geom_groups: [0, 1, 2]

pattern:
  type: "lidar_scan"
  vertical_fov_range: [-25.0, 25.0]
  horizontal_fov_range: [-25.0, 25.0]
  channels: 21
  horizontal_res: 2.5
  offset:
    pos: [0.08, 0.0, 0.15]
    rot: [0.8660, 0.0, 0.5000, 0.0]
