version: '3.8'

services:
  obelisk:
    shm_size: '12gb'
    build:
      context: ..
      args:
        USERNAME: $USERNAME
        USER_UID: $UID
        USER_GID: $GID
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
      USERNAME: ${USERNAME}
    volumes:
      - $PWD:$PWD
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 7007:7007
    working_dir: $PWD
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
