name: Core Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  code-checks:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.26.1
          cache: true
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pixi.toml') }}
      - name: Set Up Development Environment
        run: |
          shopt -s expand_aliases
          source setup.sh --recommended --leap --obk-aliases
          docker compose -f $GITHUB_WORKSPACE/docker/docker-compose-ci.yml up -d
      - name: Build and Source Obelisk ROS2 Packages
        run: |
          obk-build
      - name: Run Ruff Linter
        run: |
          docker compose -f $GITHUB_WORKSPACE/docker/docker-compose-ci.yml exec -T obelisk bash -c "$HOME/.pixi/bin/pixi run --environment dev-no-gpu ruff check docs/ obelisk/ tests/ --output-format=github"
      - name: Run Ruff Formatter
        run: |
          docker compose -f $GITHUB_WORKSPACE/docker/docker-compose-ci.yml exec -T obelisk bash -c "$HOME/.pixi/bin/pixi run --environment dev-no-gpu ruff format docs/ obelisk/ tests/ --diff"
      - name: Run Pyright
        run: |
          docker compose -f $GITHUB_WORKSPACE/docker/docker-compose-ci.yml exec -T obelisk bash -c "$HOME/.pixi/bin/pixi run --environment dev-no-gpu pyright"
      - name: Test with pytest and ctest
        run: |
          docker compose -f $GITHUB_WORKSPACE/docker/docker-compose-ci.yml exec -T obelisk bash -c "$HOME/.pixi/bin/pixi run --environment dev-no-gpu all-tests"
