name: Core Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pixi.toml') }}
      - name: Install pixi, uv, and nvm
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          curl -LsSf https://astral.sh/uv/install.sh | sh
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          source ~/.bashrc
          nvm install 20
      - name: Run Ruff Linter
        run: |
          ruff check docs/ obelisk/ tests/ --output-format=github
      - name: Run Ruff Formatter
        run: |
          ruff format docs/ obelisk/ tests/ --diff
      - name: Run Pyright
        run: |
          pyright
      - name: Test with pytest
        run: |
          pytest
