name: Core Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.24.2
          cache: true
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pixi.toml') }}
      - name: setup Development Environment
        run: |
          source dev_setup.sh --skip-docker
      - name: Build and Source ROS2
        run: |
          pixi run --environment dev-no-gpu source-obelisk
      - name: Run Ruff Linter
        run: |
          pixi run --environment dev-no-gpu ruff check docs/ obelisk/ tests/ --output-format=github
      - name: Run Ruff Formatter
        run: |
          pixi run --environment dev-no-gpu ruff format docs/ obelisk/ tests/ --diff
      - name: Run Pyright
        run: |
          pixi run --environment dev-no-gpu pyright
      - name: Test with pytest and ctest
        run: |
          pixi run --environment dev-no-gpu all-tests
