name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [deploy-sphinx]

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: 3.11
        documentation_path: ./docs/source